/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.LoginRequest;
import io.swagger.model.LoginResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-06-30T04:00:03.965Z[GMT]")
@Validated
public interface AuthenticationApi {

    @Operation(summary = "Authenticate an existing user", description = "", tags={ "authentication" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "User authenticated", content = @Content(mediaType = "application/json", schema = @Schema(implementation = LoginResponse.class))),
        
        @ApiResponse(responseCode = "400", description = "cant authenticated user", content = @Content(mediaType = "application/json", schema = @Schema(implementation = LoginResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "your username or password are incorrect", content = @Content(mediaType = "application/json", schema = @Schema(implementation = LoginResponse.class))) })
    @RequestMapping(value = "/authentication/login",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<LoginResponse> logUser(@Parameter(in = ParameterIn.DEFAULT, description = "Data access to log", required=true, schema=@Schema()) @Valid @RequestBody LoginRequest body);


    @Operation(summary = "Logs out current logged in user session", description = "", tags={ "authentication" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation") })
    @RequestMapping(value = "/authentication/logout",
        method = RequestMethod.POST)
    ResponseEntity<Void> logoutUser();

}

